Resources:
  JobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: Job-Queue-${sls:stage}
      VisibilityTimeout: 300
      MessageRetentionPeriod: 345600 # default value seconds (4 days)
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt":
            - JobDeadLetterQueue
            - Arn
        maxReceiveCount: 3 # after 2 retries move to dead queue (see aws docs)
  
  JobDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: musicassessr-dql-${sls:stage}